from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)


def generate_pdf(result, image_path=None):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    # -----------------------------
    # Title
    # -----------------------------

    story.append(
        Paragraph(
            "AI INSURANCE CLAIM REPORT",
            title
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            normal
        )
    )

    story.append(Spacer(1, 15))

    # -----------------------------
    # Vehicle Image
    # -----------------------------

    if image_path is not None:

        try:

            img = Image(image_path)

            img.drawHeight = 180
            img.drawWidth = 250

            story.append(img)

            story.append(Spacer(1, 15))

        except:
            pass

    # -----------------------------
    # Customer Information
    # -----------------------------

    story.append(
        Paragraph("Customer Information", heading)
    )

    customer_table = Table([

        ["Customer Name", result["customer_name"]],

        ["Policy Number", result["policy_number"]],

        [
            "Vehicle",
            f"{result['vehicle_make']} ({result['vehicle_year']})"
        ],

        [
            "Claim Amount",
            f"PKR {result['claim_amount']:,.0f}"
        ]

    ], colWidths=[160, 280])

    customer_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica")

    ]))

    story.append(customer_table)

    story.append(Spacer(1, 20))

    # -----------------------------
    # Damage Analysis
    # -----------------------------

    story.append(
        Paragraph("Damage Analysis", heading)
    )

    damage_table = Table([

        [
            "Damage Severity",
            result["damage_prediction"]
        ],

        [
            "Confidence",
            f"{result['damage_confidence']:.2f}%"
        ]

    ], colWidths=[160, 280])

    damage_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (0, -1), colors.beige),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey)

    ]))

    story.append(damage_table)

    story.append(Spacer(1, 20))

    # -----------------------------
    # Fraud Analysis
    # -----------------------------

    story.append(
        Paragraph("Fraud Analysis", heading)
    )

    fraud_table = Table([

        [
            "Prediction",
            result["fraud_prediction"]
        ],

        [
            "Fraud Probability",
            f"{result['fraud_probability']:.2f}%"
        ]

    ], colWidths=[160, 280])

    fraud_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (0, -1), colors.beige),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey)

    ]))

    story.append(fraud_table)

    story.append(Spacer(1, 20))

    # -----------------------------
    # Recommendation
    # -----------------------------

    story.append(
        Paragraph("AI Recommendation", heading)
    )

    if result["fraud_prediction"] == "Fraud":

        recommendation = """
        <font color="red">
        <b>High Fraud Risk</b>
        </font><br/><br/>
        Manual Investigation Recommended.
        """

    else:

        recommendation = """
        <font color="green">
        <b>Low Fraud Risk</b>
        </font><br/><br/>
        Claim appears genuine.
        """

    story.append(
        Paragraph(
            recommendation,
            normal
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Footer
    # -----------------------------

    story.append(
        Paragraph(
            "<b>Generated by AI Insurance Claim Co-Pilot</b>",
            normal
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer