from datetime import datetime


def generate_report(result):

    report = f"""
====================================================
        AI INSURANCE CLAIM REPORT
====================================================

Date:
{datetime.now().strftime("%d-%m-%Y %H:%M")}

----------------------------------------------------

Customer Name : {result['customer_name']}

Policy Number : {result['policy_number']}

Vehicle       : {result['vehicle_make']} ({result['vehicle_year']})

Claim Amount  : PKR {result['claim_amount']:,.0f}

----------------------------------------------------

DAMAGE ANALYSIS

Damage Severity : {result['damage_prediction']}

Confidence      : {result['damage_confidence']:.2f}%

----------------------------------------------------

FRAUD ANALYSIS

Prediction        : {result['fraud_prediction']}

Fraud Probability : {result['fraud_probability']:.2f}%

----------------------------------------------------

AI RECOMMENDATION

"""

    # Recommendation

    if result["fraud_prediction"] == "Fraud":

        report += "⚠ High fraud risk.\nManual investigation is recommended.\n"

    else:

        report += "✓ Claim appears genuine.\nProceed with manual verification.\n"

    report += """

----------------------------------------------------

Generated by

AI Insurance Claim Co-Pilot

====================================================
"""

    return report